#!/bin/bash

cd build/
cmake ..
cmake --build .
#if [$? -eq 0]; then
#    clear
#    /usr/src/app/1-ds_dblnklst/build/app

#    echo -e "\nDone!"
#fi

/usr/src/app/1-ds_dblnklst/build/app
echo -e "\nDone!"